rbac:
  enabled: true

serviceAccount:
  create: true
  name: 

## Image configuration
registry: brigadecore
name: brigade-github-app
## Image tags in this chart default to the value specified by appVersion in Chart.yaml
# tag: latest
# pullPolicy: "Always"

service:
  name: brigade-github-app
  type: LoadBalancer
  externalPort: 80
  internalPort: 7746

ingress:
  enabled: true
  ## Used to create an Ingress record.
  hosts:
  - brigade-ingress.westeurope.cloudapp.azure.com
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"


gateway:
  ## The author associations who are allowed to have PRs built
  ## Classes are: COLLABORATOR, CONTRIBUTOR, OWNER, NONE, MEMBER, FIRST_TIMER, FIRST_TME_CONTRIBUTOR
  ## See https://developer.github.com/v4/enum/commentauthorassociation/
  ## To completely disable pull request builds, leave this list blank.
  allowedAuthorRoles:
  - OWNER
  - MEMBER
  - COLLABORATOR

github:
  ## The x509 PEM-formatted keyfile GitHub issued for you App.
  key: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIEowIBAAKCAQEAwuvbT/05Xvrrie1LyiHBKpSLrFEJ/DW5/MpcR1UimhJvgIys
    spe3axWsh5SeeH/TSnSc9VrxMP4ogeWh1JaX6bAnOhRiJt4nXap3hcPa11Yy3VLr
    0s8KEJ/SJPexR7DPwKxWNGsA+XIdXoF/PY0ZM4aIwqmGpyNpwjaSJf/yVf0BQfqP
    i/Frdx+sdk/VjRm3DCnY9Isg+kR6q4QsQfNc/iiXadvmdIAYuTC002mbnewLpGNo
    9R9qpHPyCArRvQYWa/L23OwwqJRpPFZ3CO+wSJ8lVngZ983NBjI3s5aEBJi2CTnW
    jJ9D3crFpZNNuEnkMbt9kzx2n5oBXoPmVpsCOQIDAQABAoIBABNEWQNJFniq+MlD
    aXBrcbqRwFSiFgiWDvJL1l8+rRLpq5fbT96/XGP7Wnh0Wk2y5OHBMRqXiKu9E6fz
    WNG4qP9yaA43oZQR9XYuuW3BdEpAvPpfjevihy4pfg4lZaKeeYqj/klkIk6F1x1W
    U4tz/P+41p/XPfYbbALEfiG/cObK1POb4CWTB7q4yaU45jEDgFsmUE17av/YNazx
    MszOb4doglkncUDvhKVDeQZvOa/ocUKhf3Wa0h/wtT2W0Fu/IRV8uDExZPkqRijT
    AOgb2PpTCiRgj3bvlCxWzuRqDpVELhnYPA2om/wrckdkypGL9+lSfOdgAOlvcR8E
    AtTOR1kCgYEA+zuqHrNAvw1WWXHEUP8JJPJ0EGJcmwBTwx+/4rxg7MtIlF5qSUrQ
    4pNIpdQ/8Rl7ii5IZ64NGlzIVQu9LJoHFWemInajG7k7yvJhhB5T2oIQYdn4C/OK
    NQ3IZf/otl4ijfKUnhwa/d3Sxxmtwel0GpPUuHLcGeej3GGwFMHkMEcCgYEAxp6q
    FAABAJjfM/S3U8rvZnJIp8dibnPYoTZLIlHBDoP3GamaxqRl4cj0YHy+A2OOGSti
    xEv18zlAtXmnRll5AP4QYRah/dWH6LK2rbcgQfhZoesz8tkRmTz6fJwq4Qp97Vz5
    joPGhTLP03AxBxeHFqBqMv4yWfl4DxOLlcv++X8CgYBSa1R4Fd5bzwhQ952r5L8f
    O9sPtPUkdIsGLFhLDfnONTJuWjsMKFs2uZLPtD313qJExsJCITtzNpUSMXOyOiWw
    w/wgukLwSWhwP+v15+0idiDhuRxC73abyRXBQJ8blO5JGxfeduHz/t2zK51xTCEm
    xvC2Qhgq928uUW3uoV026QKBgQC+P8ab57EOGGBcTQC5k34i/D8Z7sMbF34eVXo8
    gmDQ/ZjYDPyDX39zeWCTd4kuh9LZyxQNANGyy1lvOvr+SL++Mp4P0XUTRdCsFVsk
    JHASoMeCcF/PMxtHVAB/EbuE2d7rWQ5180VZ2uT1G9bqex/bjYaMF661Pl9A2bDv
    qHowEwKBgGeYVITX++uYxngYsEri/c41S0KxIiB0Rc5f5x3WN3o0JuUa3MB6P5Gh
    Wp0fG9731opyU43EyDGtctfbLbLIkgTozQqyrOqwKJp8sj5bRPxmgSoilTtmElkk
    u7BPcUPDdKAW2Lm6d4E99H6Gr8MsnxqkaJhU6DLtk75MO5DPhafx
    -----END RSA PRIVATE KEY-----
  ## This represents the unique ID for a GitHub App
  ## The value can be retrieved from the main App page or any inbound webhook payloads
  appID: 34823
  ## Trigger a Check Suite on Pull Requests
  ## This will need to be set to true to enable running Check Suites on PRs originating from forks
  checkSuiteOnPR: true
  ## Set a defaultSharedSecret if you want to use this one instance of the
  ## Github gateway with multiple Brigade projects. Leave the shared secret field
  ## blank in project-level configuration and this default will be used.
  #defaultSharedSecret: 9FbwaTm04jWy92MoWzOjcsiw